
# -- Overrides the chart's computed fullname
fullnameOverride: "eth-genesis"

image:
  # -- genesis-generator container image repository
  repository: chaingremlin/eth-genesis
  # -- genesis-generator container image tag
  tag: latest
  # -- genesis-generator container pull policy
  pullPolicy: IfNotPresent

# -- Custom args for the genesis-generator container
customArgs:
- all
# -- Command replacement for the genesis-generator container
customCommand: []
 # Only change this if you need to change the default command
# -- Config file
# @default -- See `values.yaml`
config:
  el:
    genesis-config.yaml: |
      chain_id: 1695930367
      deposit_contract_address: "0x0420420420420420420420420420420420420420"
      mnemonic: "ridge cotton merit vote together distance amazing autumn tiny educate donkey time"
      el_premine:
        "m/44'/60'/0'/0/0": 1000000000ETH
        "m/44'/60'/0'/0/1": 1000000000ETH
        "m/44'/60'/0'/0/2": 1000000000ETH
        "m/44'/60'/0'/0/3": 1000000000ETH
        "m/44'/60'/0'/0/4": 1000000000ETH
        "m/44'/60'/0'/0/5": 1000000000ETH
      el_premine_addrs: {}
      genesis_timestamp: 1695930367
      genesis_delay: 240
      capella_fork_epoch: 0
      deneb_fork_epoch: 2000

  cl:
    config.yaml: |
      # Prater config

      # Extends the mainnet preset
      PRESET_BASE: 'mainnet'
      CONFIG_NAME: 'testnet'

      # Transition
      # ---------------------------------------------------------------
      # Expected August 10, 2022
      TERMINAL_TOTAL_DIFFICULTY: 0
      # By default, don't use these params
      TERMINAL_BLOCK_HASH: 0x0000000000000000000000000000000000000000000000000000000000000000
      TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 0


      # Genesis
      # ---------------------------------------------------------------
      # `2**14` (= 16,384)
      MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 4
      MIN_GENESIS_TIME: 1695368596
      GENESIS_FORK_VERSION: 0x10000000
      GENESIS_DELAY: 240

      # Forking
      # ---------------------------------------------------------------
      # Some forks are disabled for now:
      #  - These may be re-assigned to another fork-version later
      #  - Temporarily set to max uint64 value: 2**64 - 1

      # Altair
      ALTAIR_FORK_VERSION: 0x20000000
      ALTAIR_FORK_EPOCH: 0
      
      # Bellatrix
      BELLATRIX_FORK_VERSION: 0x30000000
      BELLATRIX_FORK_EPOCH: 0

      # Capella
      CAPELLA_FORK_VERSION: 0x40000000
      CAPELLA_FORK_EPOCH: 0

      # Deneb
      DENEB_FORK_VERSION: 0x50000000
      DENEB_FORK_EPOCH: 2000

      # Time parameters
      # ---------------------------------------------------------------
      # 12 seconds
      SECONDS_PER_SLOT: 12
      # 14 (estimate from Eth1 mainnet)
      SECONDS_PER_ETH1_BLOCK: 12
      # 2**0 (= 1) epochs ~1 hours
      MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 1
      # 2**8 (= 256) epochs ~27 hours
      SHARD_COMMITTEE_PERIOD: 1
      # 2**11 (= 2,048) Eth1 blocks ~8 hours
      ETH1_FOLLOW_DISTANCE: 12



      # Validator cycle
      # ---------------------------------------------------------------
      # 2**2 (= 4)
      INACTIVITY_SCORE_BIAS: 4
      # 2**4 (= 16)
      INACTIVITY_SCORE_RECOVERY_RATE: 16
      # 2**4 * 10**9 (= 16,000,000,000) Gwei
      EJECTION_BALANCE: 16000000000
      # 2**2 (= 4)
      MIN_PER_EPOCH_CHURN_LIMIT: 4
      # 2**16 (= 65,536)
      CHURN_LIMIT_QUOTIENT: 65536

      # Fork choice
      # ---------------------------------------------------------------
      # 40%
      PROPOSER_SCORE_BOOST: 40

      # Deposit contract
      # ---------------------------------------------------------------
      DEPOSIT_CHAIN_ID: 13372345
      DEPOSIT_NETWORK_ID: 13372345
      DEPOSIT_CONTRACT_ADDRESS: 0x0420420420420420420420420420420420420420
          
    mnemonics.yaml: | 
      - mnemonic: "burger apology school pelican enhance roof differ universe flee humble fat join matrix oppose evidence thrive surprise flight"
        count: 100

ingress:
  # -- Ingress resource for the HTTP API
  enabled: false
  # -- Annotations for Ingress
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # -- Ingress host
  hosts:
    - host: chart-example.local
      paths: []
  # -- Ingress TLS
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

service:
  # -- Service type
  type: ClusterIP

# -- Affinity configuration for pods
affinity: {}

# -- Image pull secrets for Docker images
imagePullSecrets: 
- name: regcred

# -- Annotations for the StatefulSet
annotations: {}

# -- Liveness probe
# @default -- See `values.yaml`
livenessProbe:
  tcpSocket:
    port: http
  initialDelaySeconds: 10
  periodSeconds: 120
  failureThreshold: 3

# -- Readiness probe
# @default -- See `values.yaml`
readinessProbe:
  tcpSocket:
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5

# -- Node selector for pods
nodeSelector: {}

persistence:
  # -- Uses an EmptyDir when not enabled
  enabled: false
  # -- Use an existing PVC when persistence.enabled
  existingClaim: null
  # -- Access mode for the volume claim template
  accessModes:
  - ReadWriteOnce
  # -- Requested size for volume claim template
  size: 1Gi
  # -- Annotations for volume claim template
  annotations: {}
  # -- Selector for volume claim template
  selector: {}
  #   matchLabels:
  #     app.kubernetes.io/name: something

# -- Pod labels
podLabels: {}

# -- Pod annotations
podAnnotations: {}

# -- Pod management policy
podManagementPolicy: OrderedReady

# -- Pod priority class
priorityClassName: null

# -- Resource requests and limits
resources: {}
# limits:
#   cpu: 500m
#   memory: 2Gi
# requests:
#   cpu: 300m
#   memory: 1Gi

# -- The security context for pods
# @default -- See `values.yaml`
securityContext:
  fsGroup: 10001
  runAsGroup: 10001
  runAsNonRoot: true
  runAsUser: 10001

# -- The security context for containers
# @default -- See `values.yaml`
containerSecurityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- How long to wait until the pod is forcefully terminated
terminationGracePeriodSeconds: 5

# -- Tolerations for pods
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

# -- Topology Spread Constraints for pods
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/
topologySpreadConstraints: []

# -- Define the PodDisruptionBudget spec
# If not set then a PodDisruptionBudget will not be created
podDisruptionBudget: {}
# minAvailable: 1
# maxUnavailable: 1

# -- Update stategy for the Statefulset
updateStrategy:
  # -- Update stategy type
  type: RollingUpdate

# -- Additional init containers
initContainers: []
# - name: my-init-container
#   image: busybox:latest
#   command: ['sh', '-c', 'echo hello']

# -- Additional containers
extraContainers: []

# -- Additional volumes
extraVolumes: []

# -- Additional volume mounts
extraVolumeMounts: []

# -- Additional ports. Useful when using extraContainers
extraPorts: []

# -- Additional env variables
extraEnv:
- name: SHADOW_FORK_RPC
  value: ""
- name: SERVER_ENABLED
  value: "true"

# - name: CL_TIMESTAMP_DELAY_SECONDS
# - value: "180"

# -- Additional env variables injected via a created secret
secretEnv: {}

initChownData:
  # -- Init container to set the correct permissions to access data directories
  enabled: true
  image:
    # -- Container repository
    repository: busybox
    # -- Container tag
    tag: "1.34.0"
    # -- Container pull policy
    pullPolicy: IfNotPresent
  # -- Resource requests and limits
  resources: {}
  #  limits:
  #    cpu: 100m
  #    memory: 128Mi
  #  requests:
  #    cpu: 100m
  #    memory: 128Mi
