global:
  main:
    network: custom_devnet
    engineEndpoint: http://{{ .Release.Name }}-execution:8551
    rpcEndpoint: http://{{ .Release.Name }}-execution:8545
    beaconEndpoint: http://{{ .Release.Name }}-beacon:5052
  checkpointSync:
    enabled: false

nethermind:
  serviceMonitor:
      enabled: false
  fullnameOverride: exec-000
  enabled: true
  image:
    repository: nethermind/nethermind
    tag: latest
  imagePullSecrets:
  - name: regcred
  p2pNodePort:
    enabled: false
  persistence:
    enabled: false
    size: 50Gi
  podLabels:
    network: custom_devnet
    node_id: '0'
    ethereum_role: execution
    consensus_client: lodestar
    execution_client: nethermind
    ethereum_instance: nethermind-lodestar-001
  jwt: ecb22bc24e7d4061f7ed690ccd5846d7d73f5d2b9733267e12f56790398d908a
  resources:
    requests:
      cpu: 2000m
      memory: 5Gi
    limits:
      cpu: 3000m
      memory: 7Gi
  extraArgs:
    - --Init.ChainSpecPath=/data/genesis.json
    - --config=none.cfg
    - --Init.IsMining=false
    - --Pruning.Mode=None
    - --JsonRpc.EnabledModules=Eth,Subscribe,Trace,TxPool,Web3,Personal,Proof,Net,Parity,Health,Rpc,Debug,Admin
    - --EthStats.Enabled=false
    - --log=DEBUG
    - --Merge.Enabled=true
  initContainers:
  - name: init-genesis
    image: alpine:latest
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
    command:
      - sh
      - -ace
      - >
        GENESIS_URI=http://eth-genesis.default.svc.cluster.local:8000/custom_config_data/chainspec.json;
        TRUSTED_SETUP_URI=http://eth-genesis.default.svc.cluster.local:8000/custom_config_data/trusted_setup.txt;
        if ! [ -f /data/genesis_init_done ];
        then
          wget -O /data/genesis.json $GENESIS_URI;
          wget -O /data/trusted_setup.txt $TRUSTED_SETUP_URI;
          apk update && apk add jq;
          cat /data/genesis.json | jq -r '.config.chainId' > /data/chainid.txt;
          touch /data/genesis_init_done;
          echo "genesis init done";
        else
          echo "genesis is already initialized";
        fi;
    volumeMounts:
      - name: storage
        mountPath: "/data"

lodestar:
  fullnameOverride: beacon-000
  enabled: true
  image:
    repository: chainsafe/lodestar
    tag: latest
    pullPolicy: Always
  mode: "beacon"
  securityContext:
    runAsNonRoot: false
    runAsUser: 0
  podLabels:
    network: custom_devnet
    node_id: '0'
    ethereum_role: consensus
    consensus_client: lodestar
    execution_client: nethermind
    ethereum_instance: nethermind-lodestar-001
  resources:
    requests:
      cpu: 2000m
      memory: 5Gi
    limits:
      cpu: 3000m
      memory: 7Gi
  p2pNodePort:
    enabled: false
    startsAt: 31004
  serviceMonitor:
    enabled: false
  jwt: ecb22bc24e7d4061f7ed690ccd5846d7d73f5d2b9733267e12f56790398d908a
  persistence:
    enabled: false
    size: 50Gi
  imagePullSecrets:
  - name: regcred
  # extraEnv: 
  #   - name: DEBUG
  #     value: discv5:service,discv5:sessionService
  extraArgs:
    - --execution.urls=http://exec-000-headless.default.svc.cluster.local:8551
    - --genesisStateFile=/data/testnet_spec/genesis.ssz
    - --paramsFile=/data/testnet_spec/config.yaml
    - --suggestedFeeRecipient=0x1F37a4D82873CAda2985dDD66d3676627a7aA3B1
    - --logLevel debug
    - --persistNetworkIdentity
    - --eth1
    - --targetPeers 2
    - --metrics=true 
  initContainers:
  - name: init-genesis
    image: alpine:latest
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
    command:
      - sh
      - -ace
      - >
        while ! wget -T 5 -c http://eth-genesis.default.svc.cluster.local:8000/; do sleep 5; done;
        DEPOSIT_CONTRACT_URI=http://eth-genesis.default.svc.cluster.local:8000/custom_config_data/deposit_contract.txt;
        DEPOSIT_CONTRACT_BLOCK_URI=http://eth-genesis.default.svc.cluster.local:8000/custom_config_data/deposit_contract_block.txt;
        DEPLOY_BLOCK_URI=http://eth-genesis.default.svc.cluster.local:8000/custom_config_data/deploy_block.txt;
        GENESIS_CONFIG_URI=http://eth-genesis.default.svc.cluster.local:8000/custom_config_data/config.yaml;
        GENESIS_SSZ_URI=http://eth-genesis.default.svc.cluster.local:8000/custom_config_data/genesis.ssz;
        TRUSTED_SETUP_URI=http://eth-genesis.default.svc.cluster.local:8000/custom_config_data/trusted_setup.txt;
        mkdir -p /data/testnet_spec;
        apk update && apk add jq;

        if ! [ -f /data/testnet_spec/genesis.ssz ];
        then
          wget -O /data/testnet_spec/deposit_contract.txt $DEPOSIT_CONTRACT_URI;
          wget -O /data/testnet_spec/deposit_contract_block.txt $DEPOSIT_CONTRACT_BLOCK_URI;
          wget -O /data/testnet_spec/deploy_block.txt $DEPLOY_BLOCK_URI;
          wget -O /data/testnet_spec/config.yaml $GENESIS_CONFIG_URI;
          wget -O /data/testnet_spec/genesis.ssz $GENESIS_SSZ_URI;
          echo "genesis init done";

        else
          echo "genesis exists. skipping...";
        fi;
    volumeMounts:
      - name: storage
        mountPath: "/data"
  serviceMonitor:
    enabled: false
